### ISSUE TITLE
Technical Error while creating New Relic Rest Client:com.neotys.newrelic.NewRelicException: No Application found for name

### ISSUE THREAD

**Issue by mbozek83** [Neotys-Labs/NewRelic#1]
Neoload Client Version: 7.0.2
Neoload license is Enterprise Edition. Integrations and advanced usage is enabled.

Been trying to use the latest version of this integration and am hitting an issue that may be a bug. Note that used this plugin about a year ago and had it working fine.

When trying to test the New Relic integration test we always end up with the following 

Technical Error while creating New Relic Rest Client:com.neotys.newrelic.NewRelicException: No Application found for name 

then whatever string we enter in the NewRelicApplicationName field.

I have tested this in two separate applications which have different new relic account.  I have double checked the appname and apikey we are using and checked the values through a direct api request.

curl -X GET 'https://api.newrelic.com/v2/applications.json' \
     -H 'X-Api-Key:#KEYHERE' -i \
     -G -d 'filter[name]=#APPNAME'

Looking through the response from the api and the code I see one respond which which I think the JSON parser should work with but I'm not terrible experienced in Java. But I don't think the bug is here.

 I have noticed that nomatter what I enter in the NewRelicApiKey gives me the same error message so perhaps it fails due to a chnage in the way api is handled.  I've scanned through the code but if there is an easy red flag I missed it.

I think a workaround solution is best for what I am planning to do but liked this intergation and thought I would submit what I have done so far to see if I overlooked something simple.

Thanks

**Comment by guillaumebert** [comment]
Hello @mbozek83 

Thank you for your feedback.
This error could be thrown if several applications match the filter "filter[name]=#APPNAME".
If you still have the issue, can you check that the output of your curl command contains only one applicatio, and starts with something like:
{"applications":[{"id":123456,......

Best regards.
